### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by samuelpatro** [MiCottOn/DejaVue#36] opened 2017-02-09 22:18 UTC
Hey, i using electron and electron-devtools-installer for installing chrome extension for electron

Error on this line
```
$('a').on('click', function (e) {
```

Thanks for pretty cool extension 👍

**Comment by kimhjona** [comment] 2017-02-10 00:46
hi samuel, thanks for the heads up. I've uploaded a fix to this, shouldn't be an issue now. 

and thanks!

**Comment by samuelpatro** [comment] 2017-02-10 09:17
Thanks, its without error, but i have still some issue, i have only showing this, if i refresh or reopen devtools its same

![obrazok](https://cloud.githubusercontent.com/assets/3110002/22821160/26a1cf16-ef7a-11e6-8c2f-69b08cf7c592.png)

**Comment by sschwartz0** [comment] 2017-02-10 16:48
Hey Sam,

After seeing the two bugs the issue is with Electron not loading the d3.min.js file due to security policies. I haven't used electron-devtools-installer before but we'll reopen this and take a look at it.

**Comment by marxcom** [comment] 2017-02-12 01:12
I don't know how to configure my files to allow $ to pass node.

I have tried many configuration for my eslintr.json file.

> Marxs-MBP:project Marx$ node consoleTest.js
/Users/Marx/Desktop/apps/project/consoleTest.js:1
(function (exports, require, module, __filename, __dirname) { $(document).ready(function () {
                                                              ^

ReferenceError: $ is not defined
    at Object.<anonymous> (/Users/Marx/Desktop/apps/project/consoleTest.js:1:63)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3



**Here is my eslint file**

{
    "env": {
        "browser": true,
        "es6": true,
        "node": true,
        "jquery": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "sourceType": "module"
    },
    "plugins": [
        "jquery"
      ],
    "rules": {
      "no-console":0,
        "indent": [
            "error",
            2
        ],
        "comma-dangle":[
          2,
          "always-multiline"
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            0,
            "double"
        ],
        "semi": [
            "error",
            "always"
        ],
            "jquery/no-ajax": 2,
            "jquery/no-animate": 2,
            "jquery/no-attr": 2,
            "jquery/no-bind": 2,
            "jquery/no-class": 2,
            "jquery/no-clone": 2,
            "jquery/no-closest": 2,
            "jquery/no-css": 2,
            "jquery/no-data": 2,
            "jquery/no-deferred": 2,
            "jquery/no-delegate": 2,
            "jquery/no-each": 2,
            "jquery/no-fade": 2,
            "jquery/no-filter": 2,
            "jquery/no-find": 2,
            "jquery/no-global-eval": 2,
            "jquery/no-has": 2,
            "jquery/no-hide": 2,
            "jquery/no-html": 2,
            "jquery/no-in-array": 2,
            "jquery/no-is": 2,
            "jquery/no-map": 2,
            "jquery/no-merge": 2,
            "jquery/no-param": 2,
            "jquery/no-parent": 2,
            "jquery/no-parents": 2,
            "jquery/no-parse-html": 2,
            "jquery/no-prop": 2,
            "jquery/no-proxy": 2,
            "jquery/no-serialize": 2,
            "jquery/no-show": 2,
            "jquery/no-size": 2,
            "jquery/no-sizzle": 2,
            "jquery/no-slide": 2,
            "jquery/no-submit": 2,
            "jquery/no-text": 2,
            "jquery/no-toggle": 2,
            "jquery/no-trigger": 2,
            "jquery/no-trim": 2,
            "jquery/no-val": 2,
            "jquery/no-wrap": 2
    }
}

**Comment by sschwartz0** [comment] 2017-02-12 01:26
Thanks. In the meantime I'd suggest looking to see a way to enable the use of loaded js files. Even without jQuery this would not work as d3.js is necessary. I'm going to close for now until we start to tackle it but to be 100% upfront we will be working on refining the chrome version before moving to other platforms.

**Closed as completed by sschwartz0** 2017-02-12 01:26 UTC
Labels: enhancement
